### ISSUE TITLE
Missing files for porting L1-regularized logistic regression models for predicting asthma figure

### ISSUE THREAD

**Issue by nhintruong** [tdhock/hla-asthma#1]
I am trying to porting the visualization of the source code [L1-regularized logistic regression models for predicting asthma](https://github.com/tdhock/hla-asthma/blob/a3dc13ac5a02302b75eb59538b6c8f63d2fb07a1/figure-asthma.R)

While attempting to run the code, I've encountered some errors due to missing files:

- **ages_toby.txt** in [hla-asthma/output.diseases.R](output.diseases.R)
- **all_autoimmune_pheno_age.tab** in [hla-asthma/all.autoimmune.R](all.autoimmune.R)
- **Autoimmune_diseases_codes_relevant.csv** and **Autoimmune_diseases_codes.csv** in [hla-asthma/all.autoimmune.R](all.autoimmune.R)
- **test.RData** in [hla-asthma/hla.R](hla.R)
- **ukbb_asthma_32markers_dosages** in [hla-asthma/markers.dosages.R](markers.dosages.R)
- **marker_positions.tsv** in [hla-asthma/input.features.R](input.features.R)

@tdhock I would be very grateful if you could recheck the availability of these files or direct me to where I might find them.

Thank you very much for your time and assistance.

**Comment by tdhock** [comment]
I don't think these files exist anymore, so it would be good if you could start a list of old gallery viz which can not be ported, and add this example to that list.

**Comment by nhintruong** [comment]
> I don't think these files exist anymore, so it would be good if you could start a list of old gallery viz which can not be ported, and add this example to that list.

 I  have created issue (https://github.com/animint/gallery/issues/7) for the non-portable visualizations. Thank you for your comment.
